### ISSUE TITLE
Fails at Step 10 While Building

### ISSUE THREAD

**Issue by 0x48756773** [ZephrFish/DockerAttack#2]
Step 10: RUN tar xvzf rockyou.tar.gz
 ---> Running in 5c24d7321bdb
tar (child): rockyou.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Looks like a few issues going on:
When opening up that docker instance, it looks like git clone is running on the root instead of /usr/share/wordlists (not sure why)
so SecLists and RobotsDisallowed were created in the root directory in my instance.

Also when cloning the latest SecLists, it looks like the RockYou Word list has moved and been renamed.
It's now:
/SecLists/Passwords/Leaked-Databases/rockyou.txt.tar.gz

Note that not only has the location changed, but the name of the file is changed from rockyou.tar.gz to rockyou.txt.tar.gz.

I was able to work around the issue by editing the DockerConfig
RUN cd SecLists/Passwords/Leaked-Databases
Run tar xvzf rockyou.txt.tar.gz

**Comment by ZephrFish** [comment]
which image are you talking about, and feel free to submit a pull request if you have a fix

**Comment by ZephrFish** [comment]
Have fixed the rockyou issue and am working on the wordlists issue

**Comment by ZephrFish** [comment]
I have added fixes to all images so this shouldn't happen now thanks for the heads up.
